# -*- coding: utf-8 -*-

'''
hive表的desc输出，用来解析表结构的meta信息，供BdpImportManager使用
'''

# size = 23
OrderChargeDesc = """
service_order_id        bigint
distribute_driver_amount        int
distribute_company_amount       int
distribute_yidao_amount int
distribute_snap         string
driver_agent_amount     int
is_fee_computed         tinyint
is_agent                tinyint
distribute_status       tinyint
create_time             int
update_time             int
end_time                int
balance_time            int
distribute_time         int
flag                    int
expect_driver_agent_amount      int
company_receipt_amount  int
driver_laowu_amount     int
rc_status               tinyint
distribute_labour_company_amount        int
distribute_fund_amount  int
labour_company_receipt_amount   int
dt                      int
"""

# size = 87
FoOrderDesc = """
service_order_id        bigint
product_type_id         int
fixed_product_id        int
is_asap                 tinyint
source                  int
platform                tinyint
status                  tinyint
rc_status               tinyint
end_status              tinyint
abnormal_mark           tinyint
flag                    bigint
account_id              bigint
user_id                 bigint
user_phone              string
passenger_name          string
passenger_phone         string
corporate_id            bigint
corporate_dept_id       int
city                    string
reason_id               int
flight_number           string
create_time             int
update_time             int
init_time               int
select_car_time         int
arrival_time            int
cancel_time             int
car_id                  int
car_type_id             int
car_type_ids            string
car_type                string
car_brand               string
driver_id               int
driver_phone            string
driver_name             string
vehicle_number          string
expect_start_time       int
expect_end_time         int
start_time              int
end_time                int
confirm_time            int
start_position          string
start_address           string
end_position            string
end_address             string
expect_start_latitude   double
expect_start_longitude  double
expect_end_latitude     double
expect_end_longitude    double
start_latitude          double
start_longitude         double
end_latitude            double
end_longitude           double
payment                 string
refund_status           tinyint
pay_method              tinyint
pay_status              tinyint
first_recharge_transaction_id   bigint
first_recharge_amount   decimal(10,2)
coupon_member_id        bigint
coupon_name             string
coupon_type             tinyint
coupon_facevalue        decimal(8,2)
discount                decimal(8,2)
version                 int
fee_version             int
balance_status          tinyint
payable                 tinyint
total_amount            decimal(8,2)
deposit                 decimal(8,2)
loan_in_credit          decimal(10,2)
pay_amount              decimal(10,2)
min_amount              decimal(10,2)
origin_amount           decimal(8,2)
origin_sharing_amount   decimal(10,2)
sharing_amount          decimal(10,2)
actual_time_length      int
dependable_distance     int
mileage                 int
system_distance         int
alitongxin_secret_no_x  string
alitongxin_subs_id      bigint
alitongxin_status       tinyint
passenger_session_id    string
last_operator           string
time_length             int
dt                      int
"""

# size = 89
OdsOrderDesc = """
service_order_id        bigint
product_type_id         int
fixed_product_id        int
city                    string
create_time             int
total_amount            float
origin_amount           decimal(20,2)
sharing_amount          float
status                  tinyint
expect_start_time       int
expect_end_time         int
start_time              int
end_time                int
user_id                 bigint
corporate_id            bigint
car_id                  int
driver_id               bigint
driver_name             string
driver_phone            string
user_type               tinyint
car_type_id             int
coupon_name             string
coupon_type             int
source                  int
coupon_facevalue        int
dependable_distance     int
actual_time_length      int
time_length             int
passenger_name          string
is_asap                 int
car_type                int
car_brand               string
vehicle_number          string
invoice                 int
start_position          string
end_position            string
coupon_member_id        bigint
msg                     string
comment                 string
reason_id               int
operator_id             int
last_operator           string
deposit                 float
pay_amount              float
is_auto_dispatch        int
app_msg                 string
regulatepan_amount      float
regulatedri_amount      float
update_time             timestamp
passenger_phone         string
origin_sharing_amount   float
pay_status              int
flag                    bigint
confirm_time            int
version                 string
app_version             string
balance_status          int
receipt_title           string
arrival_time            int
driver_night_amount     int
highway_amount          float
parking_amount          float
is_night                int
deadhead_distance       int
extension               string
driver_service_amount   int
predict_origin_amount   int
predict_amount          int
start_latitude          double
start_longitude         double
compute_amount          float
addons_amount           float
expect_start_latitude   double
expect_start_longitude  double
expect_end_latitude     double
expect_end_longitude    double
system_distance         int
mileage                 int
car_type_ids            string
regulatepan_reason      string
regulatedri_reason      string
abnormal_mark           int
runtime                 int
platform                int
user_phone              string
account_id              bigint
rc_status               int
corporate_dept_id       int
dt                      int
"""

# size = 52
FoOrderExtDesc = """
service_order_id        bigint
operator_id             int
user_type               tinyint
sms                     string
create_order_longitude  double
create_order_latitude   double
confirm_latitude        double
confirm_longitude       double
arrive_latitude         double
arrive_longitude        double
src_city_name           string
dst_city_name           string
dest_city               string
dispatch_driver_ids     string
change_driver_reason_id int
before_cancel_status    tinyint
app_version             string
driver_version          string
balance_time            int
balance_result          tinyint
preauth_status          tinyint
extra_amount            decimal(8,2)
predict_amount          decimal(10,2)
night_amount            decimal(10,2)
driver_amount           decimal(8,2)
predict_origin_amount   decimal(10,2)
predict_pay_amount      decimal(10,2)
additional_time_amount  decimal(8,2)
highway_amount          decimal(8,2)
parking_amount          decimal(8,2)
addons_amount           decimal(8,2)
addons_amount_src       string
other_amount            decimal(8,2)
runtime                 int
total_distance          int
deadhead_distance       int
is_night                tinyint
regulatepan_amount      decimal(8,2)
regulatedri_amount      decimal(8,2)
regulatepan_reason      string
regulatedri_reason      string
regulate_amount         decimal(8,2)
estimate_snap           string
app_msg                 string
comment                 string
ip                      string
order_port              int
confirm_ip              string
confirm_port            string
create_time             int
update_time             int
dt                      int
"""

# size = 25
GeoPosDesc = """
city                    string
service_order_id        bigint
user_id                 bigint
driver_id               bigint
start_time              int
end_time                int
start_position          string
start_address           string
end_position            string
end_address             string
expect_start_latitude   double
expect_start_longitude  double
expect_end_latitude     double
expect_end_longitude    double
start_latitude          double
start_longitude         double
end_latitude            double
end_longitude           double
create_order_longitude  double
create_order_latitude   double
confirm_latitude        double
confirm_longitude       double
arrive_latitude         double
arrive_longitude        double
dt                      int
"""
